#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Consultorio.Resource", IsApplication=true)]

namespace Consultorio
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int theme_black_notitlebar_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int theme_custom_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Buscar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Doc = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int LogoTLE = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int RegistroEntrada = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int RegistroSalida = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int settings = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000d
			public const int BtnAgregarEstudio = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int BtnAgregaraddConsulta = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int BuscaConsulta = 2131165194;
			
			// aapt resource value: 0x7f070023
			public const int Buscar = 2131165219;
			
			// aapt resource value: 0x7f07001b
			public const int BuscarEstudio = 2131165211;
			
			// aapt resource value: 0x7f070042
			public const int BuscarPaciente = 2131165250;
			
			// aapt resource value: 0x7f07004d
			public const int Diagnostico = 2131165261;
			
			// aapt resource value: 0x7f070051
			public const int EsCumplio = 2131165265;
			
			// aapt resource value: 0x7f07004a
			public const int Estatura = 2131165258;
			
			// aapt resource value: 0x7f070050
			public const int FechaConsulta = 2131165264;
			
			// aapt resource value: 0x7f070048
			public const int IdPacienteConsulta = 2131165256;
			
			// aapt resource value: 0x7f07004f
			public const int Indicadiones = 2131165263;
			
			// aapt resource value: 0x7f07000e
			public const int ListViewConsultas = 2131165198;
			
			// aapt resource value: 0x7f07001d
			public const int ListViewEstudios = 2131165213;
			
			// aapt resource value: 0x7f070047
			public const int ListViewPacientes = 2131165255;
			
			// aapt resource value: 0x7f07004e
			public const int Medicamento = 2131165262;
			
			// aapt resource value: 0x7f07002e
			public const int Menu_btn1 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int Menu_btn2 = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int Menu_btn5 = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int Menu_btn6 = 2131165234;
			
			// aapt resource value: 0x7f070033
			public const int Menu_lblImpresora = 2131165235;
			
			// aapt resource value: 0x7f07004c
			public const int MotivoConsulta = 2131165260;
			
			// aapt resource value: 0x7f07004b
			public const int PesoCorporal = 2131165259;
			
			// aapt resource value: 0x7f070049
			public const int PresionArterial = 2131165257;
			
			// aapt resource value: 0x7f070034
			public const int ScrollView_Paciente = 2131165236;
			
			// aapt resource value: 0x7f07003f
			public const int TXTEnfermedadesCronicas = 2131165247;
			
			// aapt resource value: 0x7f07003a
			public const int TxtDomicilio = 2131165242;
			
			// aapt resource value: 0x7f07003c
			public const int TxtEmailPaciente = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int TxtMedicamentosNoPermitidos = 2131165246;
			
			// aapt resource value: 0x7f070035
			public const int TxtNombrePaciente = 2131165237;
			
			// aapt resource value: 0x7f070040
			public const int TxtNumerodeEmergencia = 2131165248;
			
			// aapt resource value: 0x7f070038
			public const int TxtOcupacion = 2131165240;
			
			// aapt resource value: 0x7f070039
			public const int TxtReligion = 2131165241;
			
			// aapt resource value: 0x7f070019
			public const int TxtResultados = 2131165209;
			
			// aapt resource value: 0x7f07003d
			public const int TxtalergiasPaciente = 2131165245;
			
			// aapt resource value: 0x7f070025
			public const int btnAgregar = 2131165221;
			
			// aapt resource value: 0x7f070046
			public const int btnAgregarConsulta = 2131165254;
			
			// aapt resource value: 0x7f070043
			public const int btnAgregarPaciente = 2131165251;
			
			// aapt resource value: 0x7f070026
			public const int btnEditar = 2131165222;
			
			// aapt resource value: 0x7f07000c
			public const int btnEditarConsulta = 2131165196;
			
			// aapt resource value: 0x7f07001c
			public const int btnEditarEstudio = 2131165212;
			
			// aapt resource value: 0x7f070044
			public const int btnEditarPaciente = 2131165252;
			
			// aapt resource value: 0x7f070027
			public const int btnEliminar = 2131165223;
			
			// aapt resource value: 0x7f070045
			public const int btnEliminarPacienter = 2131165253;
			
			// aapt resource value: 0x7f07002c
			public const int btnIniciarSesion = 2131165228;
			
			// aapt resource value: 0x7f070001
			public const int checkBox1 = 2131165185;
			
			// aapt resource value: 0x7f070017
			public const int checkBox1Estudios = 2131165207;
			
			// aapt resource value: 0x7f070000
			public const int datePicker1 = 2131165184;
			
			// aapt resource value: 0x7f070016
			public const int datePicker1Estudios = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int estudiocuatro = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int estudiodos = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int estudiouno = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int estuditres = 2131165204;
			
			// aapt resource value: 0x7f070029
			public const int imageView1 = 2131165225;
			
			// aapt resource value: 0x7f070024
			public const int linearLayout1 = 2131165220;
			
			// aapt resource value: 0x7f07002d
			public const int linearLayout2 = 2131165229;
			
			// aapt resource value: 0x7f070030
			public const int linearLayout3 = 2131165232;
			
			// aapt resource value: 0x7f070028
			public const int listView = 2131165224;
			
			// aapt resource value: 0x7f07002b
			public const int pass = 2131165227;
			
			// aapt resource value: 0x7f07001e
			public const int textView1 = 2131165214;
			
			// aapt resource value: 0x7f070010
			public const int textodos = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int textotres = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int textouno = 2131165199;
			
			// aapt resource value: 0x7f070009
			public const int txtBuscarConsulta = 2131165193;
			
			// aapt resource value: 0x7f07001a
			public const int txtBuscarEstudios = 2131165210;
			
			// aapt resource value: 0x7f070006
			public const int txtDiagnostico = 2131165190;
			
			// aapt resource value: 0x7f070020
			public const int txtDoctorEmail = 2131165216;
			
			// aapt resource value: 0x7f070004
			public const int txtEstatura = 2131165188;
			
			// aapt resource value: 0x7f070037
			public const int txtFechaNacimiento = 2131165239;
			
			// aapt resource value: 0x7f070008
			public const int txtIndicadiones = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int txtMedicamento = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int txtMotivoConsulta = 2131165186;
			
			// aapt resource value: 0x7f070018
			public const int txtNomEstudio = 2131165208;
			
			// aapt resource value: 0x7f07001f
			public const int txtNombre = 2131165215;
			
			// aapt resource value: 0x7f070056
			public const int txtPacienteCinco = 2131165270;
			
			// aapt resource value: 0x7f070055
			public const int txtPacienteCuatro = 2131165269;
			
			// aapt resource value: 0x7f07005b
			public const int txtPacienteDiez = 2131165275;
			
			// aapt resource value: 0x7f070053
			public const int txtPacienteDos = 2131165267;
			
			// aapt resource value: 0x7f07005a
			public const int txtPacienteNueve = 2131165274;
			
			// aapt resource value: 0x7f070059
			public const int txtPacienteOcho = 2131165273;
			
			// aapt resource value: 0x7f070057
			public const int txtPacienteSeis = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int txtPacienteSiete = 2131165272;
			
			// aapt resource value: 0x7f070054
			public const int txtPacienteTres = 2131165268;
			
			// aapt resource value: 0x7f070052
			public const int txtPacienteUno = 2131165266;
			
			// aapt resource value: 0x7f070005
			public const int txtPesoCorporal = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int txtPresionArterial = 2131165187;
			
			// aapt resource value: 0x7f070036
			public const int txtSexo = 2131165238;
			
			// aapt resource value: 0x7f070021
			public const int txtTelefono = 2131165217;
			
			// aapt resource value: 0x7f07003b
			public const int txtTelefonoPaciente = 2131165243;
			
			// aapt resource value: 0x7f07002a
			public const int txtUsuario = 2131165226;
			
			// aapt resource value: 0x7f070041
			public const int txtbuscarPaciente = 2131165249;
			
			// aapt resource value: 0x7f070022
			public const int txtbuscardoctor = 2131165218;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Consultas = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DataTemplate = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DataTemplateEstudios = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Estudios = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Listas = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListasEstudios = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Menu = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Pacientes = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int TemplateConsultas = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int TemplatePaciente = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
